SELECT
  SHOP_MONTH,
  COUNT(CASE
      WHEN CUS_TYPE = "New_Customer" THEN 1
  END
    ) AS New_Customer,
  COUNT(CASE
      WHEN CUS_TYPE = "Repeat_Customer" THEN 1
  END
    ) AS Repeat_Customer,
  COUNT(CASE
      WHEN CUS_TYPE = "Reactivate_Customer" THEN 1
  END
    ) AS Reactivate_Customer,
  -(LAG(COUNT(SHOP_MONTH),1)OVER (ORDER BY SHOP_MONTH) - COUNT(CASE
        WHEN CUS_TYPE = "Repeat_Customer" THEN 1
    END
      )) AS Churn_Customer
FROM (
  SELECT
    CUST_CODE,
    SHOP_MONTH,
    CASE
      WHEN PREVIOUS_MONTH IS NULL THEN "New_Customer"
      WHEN (C_YEAR-P_YEAR)*12+(C_MONTH-P_MONTH) = 1 THEN "Repeat_Customer"
      WHEN (C_YEAR-P_YEAR)*12+(C_MONTH-P_MONTH) > 1 THEN "Reactivate_Customer"
  END
    AS CUS_TYPE
  FROM (
    SELECT
      CUST_CODE,
      SHOP_MONTH,
      CAST(SAFE.SUBSTR(CAST(SHOP_MONTH AS STRING),1,4) AS NUMERIC) AS C_YEAR,
      CAST(SAFE.SUBSTR(CAST(SHOP_MONTH AS STRING),5,2) AS NUMERIC) AS C_MONTH,
      LAG(SHOP_MONTH, 1) OVER (PARTITION BY CUST_CODE ORDER BY SHOP_MONTH) AS PREVIOUS_MONTH,
      LEAD(SHOP_MONTH, 1) OVER (PARTITION BY CUST_CODE ORDER BY SHOP_MONTH) AS NEXT_MONTH,
      CAST(SAFE.SUBSTR(CAST(LAG(SHOP_MONTH, 1) OVER (PARTITION BY CUST_CODE ORDER BY SHOP_MONTH) AS STRING),1,4) AS NUMERIC) AS P_YEAR,
      CAST(SAFE.SUBSTR(CAST(LAG(SHOP_MONTH, 1) OVER (PARTITION BY CUST_CODE ORDER BY SHOP_MONTH) AS STRING),5,2) AS NUMERIC) AS P_MONTH,
    FROM (
      SELECT
        CUST_CODE,
        CAST(SAFE.SUBSTR(CAST(SHOP_DATE AS STRING),1,6) AS NUMERIC) AS SHOP_MONTH,
      FROM
        `plated-observer-308203.supermarket_workshop.supermarket_031`
      WHERE
        CUST_CODE IS NOT NULL
      GROUP BY
        CUST_CODE,
        SHOP_MONTH
      ORDER BY
        CUST_CODE,
        SHOP_MONTH)))
GROUP BY
  SHOP_MONTH
ORDER BY
  SHOP_MONTH
